### ISSUE TITLE
add favicon in address bar or tab

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#12]
Can I add favicon?

![favicon](https://user-images.githubusercontent.com/73097560/111900693-f36d6300-8a6e-11eb-8ed5-f73a1681958f.png)

**Comment by kcoder63** [comment]
Sure, go ahead!

**Comment by vinzvinci** [comment]
Done, please link my pull request.

Link: <a href="https://github.com/kcoder63/Eddiehub_share/pull/13">https://github.com/kcoder63/Eddiehub_share/pull/13</a>

**Comment by kcoder63** [comment]
Great but next time what you could do is add `Closes <PR number>` in the pull request which will automatically close the issue when merged!

**Comment by vinzvinci** [comment]
Didn't know about that, thank you so much for reminding me. I'll do that next time :)

**Comment by kcoder63** [comment]
Yep, even I didn't know until nick told me, just passing what I learned now
