### ISSUE TITLE
create assets folder to organize other files

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#14]
I think it's better if other files like `css`, `img`  organize from `assets` folder.  The cleaner, the better.
```
- assets > css
- assets > img
- assets > js `(if ever there's javascript)`
```
`Hmm... I think ignore other files if it will affect the web content`

**Comment by kcoder63** [comment]
That'll be nice, will do that, prolly I need to update the paths from everywhere then.

**Comment by rohank2502** [comment]
Yes we can also rename everyfile and give relatable name

**Comment by kcoder63** [comment]
> Yes we can also rename everyfile and give relatable name

Why the renaming? It's already relevent I guess

**Comment by vinzvinci** [comment]
Maybe @rohank2502 mean about the numbers file name such as `1`, `23`, `6`. 
~~`~~

I suggest rename:
`1` into `mlhwelcomediscord` or `mlh-welcome-discord` (so long, but its fine) or `mlh-welcome` I guess?
`23` into `mlhform` or `mlh-form`
`6` into `chibi`

~~`~~
What do you think?

**Comment by rohank2502** [comment]
> st rename:

Exactlyy

**Comment by kcoder63** [comment]
> Maybe @rohank2502 mean about the numbers file name such as `1`, `23`, `6`.
> ~`~
> 
> I suggest rename:
> `1` into `mlhwelcomediscord` or `mlh-welcome-discord` (so long, but its fine) or `mlh-welcome` I guess?
> `23` into `mlhform` or `mlh-form`
> `6` into `chibi`
> 
> ~`~
> What do you think?

yep that will do, thank you for suggesting

**Comment by ChinmayMhatre** [comment]
I'd like to work on this issue .

**Comment by ChinmayMhatre** [comment]
> I'd like to work on this issue .

Can I go ahead with this issue  @kcoder63 ?

**Comment by kcoder63** [comment]
sure!
