### ISSUE TITLE
Github org send on community support 

### ISSUE THREAD

**Issue by rohank2502** [kcoder63/Eddiehub_share#15]
I think it should send on the community page rather than support !! What you think @kcoder63

**Comment by kcoder63** [comment]
Support page so that people don't get confused on where to raise an issue to join our org

**Comment by rohank2502** [comment]
> 
> 
> Support page so that people don't get confused on where to raise an issue to join our org

Ok but Then we should redirect then to other page and give instruction on site itself then make then read our support repo

**Comment by rohank2502** [comment]
> 
> 
> Support page so that people don't get confused on where to raise an issue to join our org

Ya that is also ok

**Comment by kcoder63** [comment]
> > Support page so that people don't get confused on where to raise an issue to join our org
> 
> Ok but Then we should redirect then to other page and give instruction on site itself then make then read our support repo

We will be giving instructions and redirects on about Eddiehub page dw about it

**Comment by rohank2502** [comment]
> 
> 
> > > Support page so that people don't get confused on where to raise an issue to join our org
> > 
> > 
> > Ok but Then we should redirect then to other page and give instruction on site itself then make then read our support repo
> 
> We will be giving instructions and redirects on about Eddiehub page dw about it

ya
