### ISSUE TITLE
Making the bottom text on the side menu aligned.

### ISSUE THREAD

**Issue by kulendu** [kcoder63/Eddiehub_share#17]
Making the bottom text on the side menu aligned. The 'EddieHub' font on the side menu **zoomed-out** and reducing the **upper-padding**.

**Before :**
![Annotation 2021-03-22 215935_LI](https://user-images.githubusercontent.com/56751963/112025043-c8f8d400-8b5a-11eb-805f-c4779de012f5.jpg)

**After :**
![Annotation 2021-03-22 220013](https://user-images.githubusercontent.com/56751963/112024905-a9fa4200-8b5a-11eb-9acb-394778999ba7.png)

@kcoder63 , please have a look at the changes and please comment if any changes are to be made further 😄 

Thank you

**Comment by kcoder63** [comment]
Thank you for contributing and making the correction!
