### ISSUE TITLE
Making changes for the index.html file

### ISSUE THREAD

**Issue by kulendu** [kcoder63/Eddiehub_share#20]
Hey @kcoder63 , I want to make some UI changes in the index page (index.html). So can I work on it??

**Comment by kulendu** [comment]
Taking about the UI changes, does this look ok, or the previous version is alright **(showed below):**

![image](https://user-images.githubusercontent.com/56751963/112051343-d4a6c380-8b77-11eb-988a-d8c9d6f5522a.png)
Like adding the logos in place of the actual texts.
<br />
And also I have fixed the ``Eddiehub --> EddieHub`` { https://github.com/kcoder63/Eddiehub_share/issues/5#issuecomment-804177077 }

**Comment by kulendu** [comment]
Ok cool. 👍

**Comment by kulendu** [comment]
@kcoder63  can we keep the UI theme same all throughout the website? it will look great 😄 . Like the **About** page is kind of a **Cyberpunk** theme and the **index** page is kind of a **dark theme**, so making all the pages the same theme will look great I guess 😅

**Comment by kcoder63** [comment]
> @kcoder63 can we keep the UI theme same all throughout the website? it will look great 😄 . Like the **About** page is kind of a **Cyberpunk** theme and the **index** page is kind of a **dark theme**, so making all the pages the same theme will look great I guess 😅

Good idea, working on it!

**Comment by kulendu** [comment]
And also @kcoder63 , the front page is looking blank, so can we discuss and add some contents or styling to the page. 
What ur opinion?????
