### ISSUE TITLE
changes in readme 

### ISSUE THREAD

**Issue by imvisp** [kcoder63/Eddiehub_share#22]
-add some pictures.
-add subtopic.
**see the changes**
![temp](https://user-images.githubusercontent.com/75424375/112118570-824ebc80-8be2-11eb-8101-6b0ce9359d40.png)

**Comment by vinzvinci** [comment]
I review your PR: <a href="https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113">https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113</a>

Also change this issue title as I suggested at your <a href="https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113">PR</a> and try to add some info.

**Comment by imvisp** [comment]
> I review your PR: [#23 (review)](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113)
> 
> Also change this issue title as I suggested at your [PR](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113) and try to add some info.

like this ?

**Comment by vinzvinci** [comment]
> > I review your PR: [#23 (review)](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113)
> > Also change this issue title as I suggested at your [PR](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113) and try to add some info.
> 
> like this ?

Yes. I just share the knowledge I get when they're reviewing issues/pr. All good now, very detailed ^_^

**Comment by imvisp** [comment]
> > > I review your PR: [#23 (review)](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113)
> > > Also change this issue title as I suggested at your [PR](https://github.com/kcoder63/Eddiehub_share/pull/23#pullrequestreview-618269113) and try to add some info.
> > 
> > like this ?
> 
> Yes. I just share the knowledge I get when they're reviewing issues/pr. All good now, very detailed ^_^

Thanks for helping 👍
