### ISSUE TITLE
add Instructions and buttons in join page

### ISSUE THREAD

**Issue by kcoder63** [kcoder63/Eddiehub_share#27]
add instructions on how to join our guild in LHD, github org and discord, create buttons for each of them in `join.html` and `join.css`

**Comment by kulendu** [comment]
@kcoder63  I want to contribute for this issue

**Comment by kcoder63** [comment]
sure, please go ahead

**Comment by kulendu** [comment]
@kcoder63 can you please elaborate the issue, like as we have given the links of GitHub, Discord and MLH in the side menu. So in the join-page we are again we are doing the same. So in the future will there be both the tabs : the **Join EddieHub** and the **Join page**

**Comment by kcoder63** [comment]
This one has a redirect from about page and the reason to make this page is that it should mainly contain instructions for new people who don't know how to and the links. This won't be shown in the homepage tho

**Comment by kulendu** [comment]
Like regarding the contents in how to join the MLH guild, should I take the content from the README. And also the button will be the same as the about page?

**Comment by kcoder63** [comment]
Yes for the mlh guild and how to join GitHub organisation

**Comment by kulendu** [comment]
Ok fine. So its gonna be like the step wise procedure with all the 'how to ' along with the links 😁

**Comment by kcoder63** [comment]
Yes!

**Comment by kulendu** [comment]
![Annotation 2021-03-25 151939](https://user-images.githubusercontent.com/56751963/112453355-9da1ff00-8d7d-11eb-9418-1268f67dd2c1.png)
![Annotation 2021-03-25 152003](https://user-images.githubusercontent.com/56751963/112453379-a397e000-8d7d-11eb-8922-162a3bc3cd94.png)

@kcoder63 please review the changes

**Comment by kcoder63** [comment]
Can we change the colour of link in MLH? I know it's by default purple but it's not really visible so add something? Plus add the link of support repo of GitHub organisation in how to join our GitHub org please

**Comment by kulendu** [comment]
I have added the link for the github issue section as 'here'. But the problem is same with the LHD: Share link as well. 


So I can fix it or just can we add an kind of logo or an small image for the links??

**Comment by kcoder63** [comment]
I think we have two logos in assets folder which we used in our side menu too, would that work here?

**Comment by kulendu** [comment]
Yes that can be added here. And if not Im putting a small logo for the substitute is it fine?

**Comment by kcoder63** [comment]
Yeah cool
