### ISSUE TITLE
add links in Join EddieHub section 

### ISSUE THREAD

**Issue by kcoder63** [kcoder63/Eddiehub_share#3]
add links and change sub item names to their respective names in `Join EddieHub` section in [index.html](https://github.com/kcoder63/Eddiehub_share/blob/main/index.html)

1. Github Org link in join eddiehub [github org](https://github.com/EddieHubCommunity/support)
2. Discord server [discord](https://discord.com/invite/PNHRZJf7v7)
3. Join eddiehub in lhd share [MLH discord](https://discord.mlh.io)

**Comment by sudiptog81** [comment]
Getting it done :smile:

**Comment by kcoder63** [comment]
awesome! thank you
