### ISSUE TITLE
align sub-item inside the Forms

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#37]
`suggestion:`
I think it's better if we put these text on the **left side**, **not on cente**r cause this will really force the text to move to another line. What do you think?

![leftside](https://user-images.githubusercontent.com/73097560/112261200-5a289180-8ca6-11eb-8f73-532ce3b1d673.png)

**Comment by kcoder63** [comment]
Yes, I was thinking to remove `form` from it because it looked too long and moved to other line but this idea is great! Thanks

**Comment by vinzvinci** [comment]
> Yes, I was thinking to remove `form` from it because it looked too long and moved to other line but this idea is great! Thanks

Hmm yeah, let me see if I can fix this. Give me a time xD

**Comment by bishalr0y** [comment]
I want to work on this issue

**Comment by bishalr0y** [comment]
![2021-03-24 16_11_25-EddieHub](https://user-images.githubusercontent.com/56751927/112297249-ad590f00-8cbb-11eb-895e-2a0e069fb0c5.png)
I have fixed the padding-left. Is it looking right now?

**Comment by kcoder63** [comment]
Yepp! Awesome
