### ISSUE TITLE
label is missing on issues template

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#38]
There's no labels when I'm using issues template. 

`I used Feature request template`
![lable](https://user-images.githubusercontent.com/73097560/112262149-1fbff400-8ca8-11eb-833c-3aaf7edcfc2e.png)

**Comment by vinzvinci** [comment]
Also this issue, doesn't have `bug` label

**Comment by kcoder63** [comment]
Will fix it today, thanks for letting me know
