### ISSUE TITLE
resize the text at about page

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#40]
Should we resize the text at `about.html`? For me this is too big and the nearsighted people will hurt their eye.

`just make it balance`  | `not too little and not too big`
![Untitled](https://user-images.githubusercontent.com/73097560/112404644-ada0eb00-8d4b-11eb-8d96-bd13a9deedc7.png)

**Comment by kcoder63** [comment]
Yes sure, you're good at noticing things. You did help me a lot in improvements, thank you!

**Comment by bishalr0y** [comment]
![image](https://user-images.githubusercontent.com/56751927/112428870-d7fda300-8d61-11eb-9b3e-6d1f077fb1ce.png)

Is this font size looking right?
