### ISSUE TITLE
Adding the Footer section

### ISSUE THREAD

**Issue by kulendu** [kcoder63/Eddiehub_share#46]
Adding a common **footer section** which can be added in all the pages.

**Comment by kcoder63** [comment]
How about something like this? A quote maybe?
![Screenshot_2021-03-25-20-45-21-046_com android chrome](https://user-images.githubusercontent.com/74637789/112497026-3bf88980-8dab-11eb-94d8-a3aad8d40847.jpg)

**Comment by kulendu** [comment]
Not bad. But what about adding something minimal, like adding something that goes well with every pages

**Comment by kcoder63** [comment]
Just © EddieHub? What do you have in mind? Or a small contact section?

**Comment by kulendu** [comment]
![Annotation 2021-03-25 225419](https://user-images.githubusercontent.com/56751963/112516212-0eb4d700-8dbd-11eb-9545-56a1994943f1.png)
@kcoder63 what about something like this

**Comment by kcoder63** [comment]
On the top? Shouldn't footer be below?

**Comment by kulendu** [comment]
ya but its not like an footer, but more like a link for the repo to this project.

What should prefer?? The footer or this sort of thing

**Comment by kulendu** [comment]
@kcoder63 I think this looks minimal and standard
![Annotation 2021-03-25 235942](https://user-images.githubusercontent.com/56751963/112524836-44aa8900-8dc6-11eb-88dc-25de8488dfea.png)
