### ISSUE TITLE
add information about Eddiehub

### ISSUE THREAD

**Issue by kcoder63** [kcoder63/Eddiehub_share#5]
Add information about EddieHub in the `About` section of our sidebar menu or make a redirect to an About page

**Comment by bishalr0y** [comment]
Hey, I want to work on this issue. Can you guide me on how to get started?

**Comment by kcoder63** [comment]
Sure, have a look at the GitHub page for the about section, we need to add some information in about.html in the respective sections like about eddiehub, achievements etc

**Comment by bishalr0y** [comment]
Can you please specify the information that needs to be added in the sections.

**Comment by vinzvinci** [comment]
I suggest embed this **youtube** video:
Link: <a href="https://www.youtube.com/watch?v=z-FKAC0I_VQ">https://www.youtube.com/watch?v=z-FKAC0I_VQ</a>
![ed](https://user-images.githubusercontent.com/73097560/111952468-2b80ae80-8b20-11eb-8495-b2955854a419.png)

<hr />

I think this information in the `readme` should be added below the video? 
![Untitled](https://user-images.githubusercontent.com/73097560/111951718-00498f80-8b1f-11eb-970e-f52d247a916a.png)

**Comment by kcoder63** [comment]
yes we can, but I'd suggest to remove the line from "you'll find...." since it's not discord

**Comment by kcoder63** [comment]
![blah](https://user-images.githubusercontent.com/74637789/111956465-cf625e00-8b10-11eb-9278-8b219dacab9a.png)
 who would like to remove these blahs here? 😉

**Comment by vinzvinci** [comment]
Yeah, let's wait for the upcoming video.

How about this?
`We believe Open Source is for everyone, yes you! Open Source is not about code, it is about people and collaboration. We are invested in getting you those green squares on GitHub! Contributing to Open Source Software (OSS) is a great way for you to learn, work with different people and also network.`

Hmm just suggest what do you think is better.

You can do this @bishalr0y issue

**Comment by kcoder63** [comment]
we could add how to join github org since people get confused or don't find it easily plus how to join our guild too, the instructions are missing, we have added the links

**Comment by kcoder63** [comment]
> Yeah, let's wait for the upcoming video.
> 
> How about this?
> `We believe Open Source is for everyone, yes you! Open Source is not about code, it is about people and collaboration. We are invested in getting you those green squares on GitHub! Contributing to Open Source Software (OSS) is a great way for you to learn, work with different people and also network.`
> 
> Hmm just suggest what do you think is better.
> 
> You can do this @bishalr0y issue

yes that's good

**Comment by bishalr0y** [comment]
> Yeah, let's wait for the upcoming video.
> 
> How about this?
> `We believe Open Source is for everyone, yes you! Open Source is not about code, it is about people and collaboration. We are invested in getting you those green squares on GitHub! Contributing to Open Source Software (OSS) is a great way for you to learn, work with different people and also network.`
> 
> Hmm just suggest what do you think is better.
> 
> You can do this @bishalr0y issue

So, I just need to add only this text inside the about section.

**Comment by kcoder63** [comment]
yes in about.html inside the `<p>` tags

**Comment by bishalr0y** [comment]
![2021-03-22 13_36_31-](https://user-images.githubusercontent.com/56751927/111958813-b27b5a00-8b13-11eb-813a-f23a2899ce6e.png)
I have added the text using the <p> tag. But the text is not getting displayed on the webpage. Can you help me to figure out why it is not working.

**Comment by kcoder63** [comment]
Oops looks like you're doing it on old one, I have updated the about.html , clone this one and try

**Comment by bishalr0y** [comment]
> Oops looks like you're doing it on old one, I have updated the about.html , clone this one and try

Alright.

**Comment by bishalr0y** [comment]
What should I add inside the "Why should you join EddieHub?" section?

**Comment by vinzvinci** [comment]
> What should I add inside the "Why should you join EddieHub?" section?

Maybe we need help from our discord server.

**Comment by Zipher007** [comment]
> What should I add inside the "Why should you join EddieHub?" section?

Actually i've tried to write something for this section. We can see how that looks and do some changes if necessary!

At EddieHub we provide a hands-on learning experience for young open source enthusiasts who are passionate to contribute, learn and grow together as a community.
We believe that open-source is not just defined by coding! 
A collaborative approach is what we follow and encourage each member to interact and “Code In Public”. 

Join a fast-growing community as everyone has a role to play here.

**Comment by divyakumari12** [comment]
![eddie](https://user-images.githubusercontent.com/73889049/111982617-2f67fd00-8b2f-11eb-8ac2-fec304a143d5.JPG)


What about This??

**Comment by kcoder63** [comment]
hey @Zipher007 @divyakumari12 thank you! both the texts are really nice, I'd like to add a mix of both and make it a little LHD guild specific like by adding Eddiehub's achievement in previous LHD. We need some clear instructions below on how to join in our guild as given in readme already and how to join our github organisation which is raising an issue on the support repo of eddiehub. I'll put up the redicrects once done, what do you say?

**Comment by Zipher007** [comment]
Yeah

> hey @Zipher007 @divyakumari12 thank you! both the texts are really nice, I'd like to add a mix of both and make it a little LHD guild specific like by adding Eddiehub's achievement in previous LHD. We need some clear instructions below on how to join in our guild as given in readme already and how to join our github organisation which is raising an issue on the support repo of eddiehub. I'll put up the redicrects once done, what do you say?

Yeah @kcoder63 thats definitely a good idea and it will also be really helpful for beginners like me to get to know about EddieHub and join our community.
Also, pls let me know if there is anything i can help with as well !

**Comment by kcoder63** [comment]
Maybe try adding instructions from README for how to join our guild? I'll handle the GitHub org's instructions

**Comment by bishalr0y** [comment]
> Maybe try adding instructions from README for how to join our guild? I'll handle the GitHub org's instructions

I think we should add this on a separate page not on the about page. What is your opinion?

**Comment by bishalr0y** [comment]
![2021-03-22 17_46_28-](https://user-images.githubusercontent.com/56751927/111988512-976e1180-8b36-11eb-8aab-65d2c14e67b0.png)
Is is this looking good?

**Comment by kcoder63** [comment]
What do you think? Will it look good on different page or this is fine? I'll let y'all decide

**Comment by bishalr0y** [comment]
> What do you think? Will it look good on different page or this is fine? I'll let y'all decide

I think providing a "join" button at the end of the page that takes the user to a separate joining page will look good.

**Comment by kcoder63** [comment]
> > What do you think? Will it look good on different page or this is fine? I'll let y'all decide
> 
> I think providing a "join" button at the end of the page that takes the user to a separate joining page will look good.

Would you like to redirect it to `Join EddieHub` since we have already put the three links at one place
![IMG_20210322_180936](https://user-images.githubusercontent.com/74637789/111991327-30525c00-8b3a-11eb-9994-ef001ec71bdd.jpg)

**Comment by bishalr0y** [comment]
> > > What do you think? Will it look good on different page or this is fine? I'll let y'all decide
> > 
> > 
> > I think providing a "join" button at the end of the page that takes the user to a separate joining page will look good.
> 
> Would you like to redirect it to `Join EddieHub` since we have already put the three links at one place
> ![IMG_20210322_180936](https://user-images.githubusercontent.com/74637789/111991327-30525c00-8b3a-11eb-9994-ef001ec71bdd.jpg)

Yeah, I can try to do that. For that I would have to add a button at the end of the page. Do you have a pre-styled button, so that I can put it up there or should I design a button?

**Comment by kcoder63** [comment]
I don't have a pre styled one, you can try if you like to

**Comment by bishalr0y** [comment]
I am not sure about how can I redirect user to a portion of the mobile menu. Can you open another issue for that?

**Comment by kcoder63** [comment]
Maybe making another page would be best option, we could add instructions there

**Comment by bishalr0y** [comment]
> Maybe making another page would be best option, we could add instructions there. We can just use this theme for that too right? Add a button and redirect to new joining page with instructions and links

Yes, we can use the same theme for the joining page too. I will try to work on that.

**Comment by kcoder63** [comment]
Awesome! Thank you, your contribution means a lot!

**Comment by bishalr0y** [comment]
> Awesome! Thank you, your contribution means a lot!

I am thinking of another PR for the joining page.
Can you check the existing PR.

**Comment by bishalr0y** [comment]
> Yes I did look at it, we might have to add a button there in the existing PR before the second PR

Ok sure

**Comment by bishalr0y** [comment]
![before](https://user-images.githubusercontent.com/56751927/112006514-c9d53a00-8b49-11eb-9cca-5a34d0354fcd.png)
![after](https://user-images.githubusercontent.com/56751927/112006518-cb066700-8b49-11eb-8f9d-c4b07f14f4d3.png)
Is this looking right?

**Comment by kcoder63** [comment]
> ![before](https://user-images.githubusercontent.com/56751927/112006514-c9d53a00-8b49-11eb-9cca-5a34d0354fcd.png)
> ![after](https://user-images.githubusercontent.com/56751927/112006518-cb066700-8b49-11eb-8f9d-c4b07f14f4d3.png)
> Is this looking right?

Yes nice!

**Comment by kcoder63** [comment]
> Heyy @kcoder63 I see you are using the Join Eddiehub button in the Mobile UI, you can also write it as Join EddieHub, like capitalize the H. It would give a good look to it.
> 
> ![image](https://user-images.githubusercontent.com/13515337/112018340-79afa500-8b54-11eb-8de3-343cd69199de.png)

Thank you for pointing it out, will fix it!

**Comment by bishalr0y** [comment]
> > ![before](https://user-images.githubusercontent.com/56751927/112006514-c9d53a00-8b49-11eb-9cca-5a34d0354fcd.png)
> > ![after](https://user-images.githubusercontent.com/56751927/112006518-cb066700-8b49-11eb-8f9d-c4b07f14f4d3.png)
> > Is this looking right?
> 
> Yes nice!

Thank you, I have added that to the PR.

**Comment by vinzvinci** [comment]
I highlight wrong spelling. Please someone fix this, also the site can't scroll and I can't see other words there. I need to zoom out my web browser just to see other information.

Here's the picture:
![spelling](https://user-images.githubusercontent.com/73097560/112074189-b6a98500-8bb0-11eb-8289-21f74cc72192.png)

**Comment by kcoder63** [comment]
This is the problem I found : there are lots of absolute positions and if we make it relative the text and the page looks wayyy bad. What we could do is create a gif for this without text and add it as bg. If anyone has any other ideas I'm all ears.

**Comment by bishalr0y** [comment]
> This is the problem I found : there are lots of absolute positions and if we make it relative the text and the page looks wayyy bad. What we could do is create a gif for this without text and add it as bg. If anyone has any other ideas I'm all ears.

I also saw some sass code inside a css file which was causing my css linter to go crazy. I had to recheck if I broke something. Maybe we can make a sass file to move the sass codes into it or we have remove all the sass code and use plain css for that.
And regarding background, it is a good idea to use gifs for background,  we can create custom gifs or use one from giphy.com

**Comment by kcoder63** [comment]
> > This is the problem I found : there are lots of absolute positions and if we make it relative the text and the page looks wayyy bad. What we could do is create a gif for this without text and add it as bg. If anyone has any other ideas I'm all ears.
> 
> I also saw some sass code inside a css file which was causing my css linter to go crazy. I had to recheck if I broke something. Maybe we can make a sass file to move the sass codes into it or we can remove all the sass code and use plain css for that.
> And regarding background, it is a good idea to use gifs for background, we can create custom gifs or use one from giphy.com

Yeah gif is better than all of this extra work, I found one which might go well

**Comment by kcoder63** [comment]
update: Made changes to about page, hopefully it goes with the dark theme too now

**Comment by kcoder63** [comment]
@all-contributors please add @eddiejaoude for documentation

**Comment by kcoder63** [comment]
@all-contributors please add @vinzvinci for code

**Comment by kcoder63** [comment]
@all-contributors please add @rohank2502 for code

**Comment by kcoder63** [comment]
@all-contributors please add @Vyvy-vi for ideas

**Comment by kcoder63** [comment]
@all-contributors please add @ChinmayMhatre for maintainance

**Comment by kcoder63** [comment]
@all-contributors please add @ChinmayMhatre for maintenance

**Comment by kcoder63** [comment]
@all-contributors please add @kulendu  for code and ideas

**Comment by kcoder63** [comment]
@all-contributors please add @imvisp  for code

**Comment by kcoder63** [comment]
@all-contributors please add @bishalr0y  for code

**Comment by kcoder63** [comment]
@all-contributors please add @divyakumari12  for ideas

**Comment by kcoder63** [comment]
@all-contributors please add @Zipher007  for ideas

**Comment by kcoder63** [comment]
@all-contributors please add @muthuannamalai12  for code

**Comment by kcoder63** [comment]
@all-contributors please add @sudiptog81  for code

**Comment by kcoder63** [comment]
@all-contributors please add @PulkitSinghDev  for code

**Comment by PulkitSinghDev** [comment]
> @all-contributors please add @PulkitSinghDev for code

😄
