### ISSUE TITLE
Link in read me 

### ISSUE THREAD

**Issue by rohank2502** [kcoder63/Eddiehub_share#63]
**Describe the bug**

The link in read me is not styled properly it is showing the URL as well 

**Screenshots**

**Additional context**

**Comment by rohank2502** [comment]
Will like to fix that !!

**Comment by kcoder63** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> The link in read me is not styled properly it is showing the URL as well
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

which links? could you describe it properly?

**Comment by rohank2502** [comment]
Its Working now when i saw It was not Sorry for inconvenience !!
