### ISSUE TITLE
Add Contributors !!

### ISSUE THREAD

**Issue by rohank2502** [kcoder63/Eddiehub_share#64]
**Is your feature request related to a problem? Please describe.**

I will like to add the contributor img at the bottom of read me that will keep the contributors list updated automatically !

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots

**Comment by kcoder63** [comment]
I was doing that right now, just as you opened this issue lol

**Comment by rohank2502** [comment]
> 
> 
> I was doing that right now, just as you opened this issue lol

No issues link your PR with this issue !

**Comment by kcoder63** [comment]
the bot does that, can't link them
