### ISSUE TITLE
Issue Regarding Website Flow

### ISSUE THREAD

**Issue by rohank2502** [kcoder63/Eddiehub_share#66]
**Describe the bug**

When we go to about section we don't get button to comeback to home section or to navigate to other section !!
If we add the navigation bar to the about page this will work !!

**Comment by kcoder63** [comment]
sure,thanks

**Comment by bishalr0y** [comment]
I want to work on this issue. Do we need to add a button to jump back to the home page?

**Comment by kcoder63** [comment]
the whole side nav bar like on home page would look better or a button?

**Comment by bishalr0y** [comment]
> the whole side nav bar like on home page would look better or a button?

According to me, navbar looks good only on home page. So, we can add a button inside the about and join page to jump to the home page. What are your thoughts on this?

**Comment by kcoder63** [comment]
sure!

**Comment by ChinmayMhatre** [comment]
IMHO Adding the navbar in all the pages will make the website look consistent .

**Comment by kcoder63** [comment]
I thought so but suggestions won't hurt, let's decide and start working on it

**Comment by ChinmayMhatre** [comment]
For sure!

**Comment by bishalr0y** [comment]
> I thought so but suggestions won't hurt, let's decide and start working on it

So what should I do? Put the navbar in all the pages?

**Comment by rohank2502** [comment]
> 
> 
> I thought so but suggestions won't hurt, let's decide and start working on it

Create a discussion tab on this issue

**Comment by bishalr0y** [comment]
I just realized one thing, the code use for the menu bar is inline jquery and involves a lot of html and css. Using the same navbar in all the pages  would use a lot of code repetition. In order to reduce code repetition and  use the same navbar across all the files, we have to create a separate script file and use some sort of partials.

**Comment by kcoder63** [comment]
yeah at first I thought we will be using at just one place so that will be fine but looks like we have to modify it. True that the code will be repeated if we don't take another way

**Comment by rohank2502** [comment]
Whos Working on this issue then ?

**Comment by bishalr0y** [comment]
> Whos Working on this issue then ?

I am not sure how to approach it, if @kcoder63 is not working on it then you can give it a go.

**Comment by kcoder63** [comment]
I'll work on it

**Comment by rohank2502** [comment]
> 
> 
> I'll work on it

Get assigned

**Comment by kcoder63** [comment]
[](http://www.menucool.com/ddmenu/one-menu-for-all-pages) how about this method? not sure how it works,if anyone is familiar with it?

**Comment by bishalr0y** [comment]
> [link](http://www.menucool.com/ddmenu/one-menu-for-all-pages) how about this method? not sure how it works,if anyone is familiar with it?

No, I am not familiar with it, looks good though.

We can also use bootstrap navbar, in it we just have to use the same markups in all the pages.  What are your views on it?
[link](https://getbootstrap.com/docs/4.0/components/navbar/)

**Comment by kcoder63** [comment]
This looks good, yes let's try this.

**Comment by bishalr0y** [comment]
> This looks good, yes let's try this.

Are you going to work on this?

**Comment by kcoder63** [comment]
Yes, I'll give it a try till evening and update you if that works well, hopefully

**Comment by bishalr0y** [comment]
> Yes, I'll give it a try till evening and update you if that works well, hopefully

Its alright, I know you can make it work😁

**Comment by kcoder63** [comment]
UPDATE - so I did try two three styles and I tried putting the nav bar for all the pages but it's not really coming together. 
![style](https://user-images.githubusercontent.com/74637789/112742884-3a4be300-8fb0-11eb-936e-4e94c3eb4fb1.png)

I tried putting on the links so that we can navigate it side by side, but it's not working. I can see the link but its not redirecting to it

**Comment by bishalr0y** [comment]
> UPDATE - so I did try two three styles and I tried putting the nav bar for all the pages but it's not really coming together.
> ![style](https://user-images.githubusercontent.com/74637789/112742884-3a4be300-8fb0-11eb-936e-4e94c3eb4fb1.png)
> 
> I tried putting on the links so that we can navigate it side by side, but it's not working. I can see the link but its not redirecting to it

Did you try putting bootstrap and jquery cdn in all the pages?

**Comment by kcoder63** [comment]
oops looks like I missed jquery

**Comment by bishalr0y** [comment]
> oops looks like I missed jquery
> 
> what do you think about this tho?
> [link](https://forums.asp.net/t/2145711.aspx?Same+navbar+on+multiple+pages)

Looks good to me. Try using it to see how it looks.

**Comment by kcoder63** [comment]
so I tried it, works fine but needs few corrections. I put the nav bar on all the pages their background and font changes as of in the front page which is not good
![nav](https://user-images.githubusercontent.com/74637789/113307475-c9475b00-9322-11eb-8e24-a4245867778e.png)

**Comment by kcoder63** [comment]
Update : I solved it wohoo!
![solved](https://user-images.githubusercontent.com/74637789/113307826-2e02b580-9323-11eb-89ec-db41da2c9dc8.png)

**Comment by bishalr0y** [comment]
Good work @kcoder63

**Comment by kcoder63** [comment]
Could you look at the site once and if there's anything else to change? Not in a hurry but whenever you get time

**Comment by bishalr0y** [comment]
> Could you look at the site once and if there's anything else to change? Not in a hurry but whenever you get time

Yeah sure.

**Comment by bishalr0y** [comment]
The navbar is not visible inside the about page. Is this was intentional?

**Comment by kcoder63** [comment]
Nope, I tried to add it to that too but I don't know what problem is there. Wasn't intentional

**Comment by bishalr0y** [comment]
> Nope, I tried to add it to that too but I don't know what problem is there. Wasn't intentional

Alright, I will try to add that and there is some position issue of the navbar inside the join page.

I will try to fix that

**Comment by kcoder63** [comment]
Yeah I experienced that problem too but I was like let's put it down here so that if anyone knew they could help

**Comment by bishalr0y** [comment]
Yeah, I'll try to fix that
