### ISSUE TITLE
[Feature] Making improvements over the contents on the main page

### ISSUE THREAD

**Issue by kulendu** [kcoder63/Eddiehub_share#77]
**Is your feature request related to a problem? Please describe.**
- The home page looks very blank. Like there is only a single text written in the whole of the page i.e. **EddieHub**.

![Annotation 2021-03-27 012803](https://user-images.githubusercontent.com/56751963/112686445-f5cf2300-8e9b-11eb-9d67-71da78f22068.png)

**Describe the solution you'd like**
- So the solution I came up with is that instead of the simple blank **EddieHub** text, we can add something like an animated text and also describe a bit what this website is all about. The reason behind this is that when our website is going to be live users would not come to our README file and read all the instructions. So to make it easy for the users I came up with this idea/feature.
- The animated **EddieHub** can be something like this : 

https://user-images.githubusercontent.com/56751963/112686983-c967d680-8e9c-11eb-88a1-5fe1ba59ad38.mp4

**Describe alternatives you've considered**
- New ideas or improvements over the old ones are always welcomed and appreciated.

**Comment by kcoder63** [comment]
You come up with really good ideas, this is really nice. We can put up a short description like `collaboration first code second` or put up that this is LHD share guild (name) site something like that

**Comment by kulendu** [comment]
Thanks @kcoder63 and yes I think the first quote goes well. So should I start working upon it.

**Comment by kcoder63** [comment]
Sure!

**Comment by rohank2502** [comment]
> 
> 
> Thanks @kcoder63 and yes I think the first quote goes well. So should I start working upon it.

@kcoder63  Can we add footer which we add for about page

**Comment by vinzvinci** [comment]
Awesome idea!

**Comment by rohank2502** [comment]
@kulendu    Do consider for this change 
![Eddie hub](https://user-images.githubusercontent.com/76584243/112718729-e5aa5880-8f1a-11eb-8be1-494af5cbb7cb.png)

**Comment by kulendu** [comment]
Hey @rohank2502 as I was already working on this issue you can definitely work on some other issues or even develop the pre-existing features to make it more awesome. And regarding the addition of the footer, I think (my POV) that the footer will not look good on the home page, as there is already the EddieHub written quite close to the bottom part. So adding the footer section will look a bit messy. This is my opinion, but you can do anyways and also what others think about the idea.
