### ISSUE TITLE
 adding tag line 

### ISSUE THREAD

**Issue by rohank2502** [kcoder63/Eddiehub_share#79]
Can we go for this ?
![Eddie hub](https://user-images.githubusercontent.com/76584243/112716166-c277ad00-8f0a-11eb-9f6e-3e7d5a4ce1a4.png)

**Comment by vinzvinci** [comment]
That will be cool.

**Comment by kcoder63** [comment]
@kulendu is already working on it and there's an issue opened for it, please look at the issues open and then open a new one, duplicates will confuse others
