### ISSUE TITLE
docs: place badges at top of the topic & update the visitors count/badge

### ISSUE THREAD

**Issue by vinzvinci** [kcoder63/Eddiehub_share#81]
We should not put these badges below the topic. I suggest put that badges at top of the topic .
Example:
`badges here` 

`What is LHD: Share?`

<hr />

![replace](https://user-images.githubusercontent.com/73097560/112716904-1b077400-8f24-11eb-9e0c-ad30e5d3fc08.png)

Question:
- I think we should update the visitors count 

![bug](https://user-images.githubusercontent.com/73097560/112716778-6a997000-8f23-11eb-95f9-ee110a0ceacf.png)

Also notice @rohank2502 username: 

![user](https://user-images.githubusercontent.com/73097560/112716852-c7952600-8f23-11eb-94af-5664ad5206c5.png)

<hr />
Closes #82

**Comment by kcoder63** [comment]
oops didn't see that there

**Comment by vinzvinci** [comment]
No worries. I already fixed it

**Comment by kcoder63** [comment]
yep merged,thanks
