### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by bishalr0y** [kcoder63/Eddiehub_share#83]
We can use comments in the html and css files to specify for what purpose the specific code is being used. 

This will:
1. Increase the readability of the code.
2. Make the code maintenance process easier.
3. Make adding new code and modifying the existing one a lot easier.

**Comment by kcoder63** [comment]
great idea, thank you!

**Comment by bishalr0y** [comment]
I think we should change the label to **enhancement**
