### ISSUE TITLE
make art gallery interactive

### ISSUE THREAD

**Issue by kcoder63** [kcoder63/Eddiehub_share#87]
**Is your feature request related to a problem? Please describe.**
The art gallery just shows the collage image which is hard coded
**Describe the solution you'd like**
making the art gallery open for other members so that they can upload their work and it can be seen without hard coding everything or changing the image
**Describe alternatives you've considered**
can we do it with flask? I know just the basics but this can help us complete two challenges at a time, build something with starter pack and a website for your guild
**Additional context**
Add any other context or screenshots

**Comment by Vyvy-vi** [comment]
I think Flask would be an amicable solution
Moreover, we can deploy flask-sites on Heroku through a github-heroku pipeline, making it easy to manage deployments

**Comment by kcoder63** [comment]
cool, when should we start working on it? It's a weekly challenge I guess
