### ISSUE TITLE
Transparency of the menu bar is too less

### ISSUE THREAD

**Issue by bishalr0y** [kcoder63/Eddiehub_share#92]
**Describe the bug**
The transparency of the meu bar is too less, though it looks fine in the home page but it breaks the about page.

**Screenshots**
![before](https://user-images.githubusercontent.com/56751927/113377120-0ba78100-9391-11eb-830b-a88999842db4.png)

**Possible Solutions**
1. Make the background color of the menu bar a solid one.
2. Decrease the transparency of menu bar.

**Comment by kcoder63** [comment]
sudipto worked on it, he added the flask backend, so everything is almost fixed
